# config/countries_cities.yml
- name: kazakhstan
  cities:
    - astana
    - almaty
    - aktobe
    - atyrau
    - karaganda
    - oskemen
    - pavlodar
    - shymkent
    - taraz
    - semey
    - ust-kamenogorsk
    - kyzylorda
    - kostanay
    - petropavl
    - oral
- name: kyrgyzstan
  cities:
    - bishkek
    - djalal-abad
    - karakol
    - osh
    - talas
    - naryn
    - batken
    - tokmok
    - uzgen
- name: uzbekistan
  cities:
    - toshkent
    - namangan
    - samarkand
    - andijan
    - nukus
    - bukhara
    - khiva
    - termez
    - qarshi
    - fergana
    - urgench
    - navoiy